### ISSUE TITLE
Make #getTerm allow empty values

### ISSUE THREAD

**Issue by luuse** [luuse/spock#12]
Copied from [this](https://github.com/luuse/spock/pull/6#issuecomment-103770433) discussion.

The `getTerm` regexp, it will match the following wrong

```
| birth_place     = [[Allentown, Pennsylvania]], [[U.S.]]
| death_date      =
| death_place     =
| abc     = 123

```

When doing `getTerm(text, "death_date")` it will match all the way down to death_place.

**Comment by luuse** [comment]
This is in `InfoBoxTrait`.

**Comment by brodin** [comment]
Solved by https://github.com/luuse/spock/commit/966d5050dec97e4850d5787a432521131eb147d5
