### ISSUE TITLE
Write a continuous JSON array to the destination instead of several separate documents

### ISSUE THREAD

**Issue by luuse** [luuse/spock#13]
In `Fetcher.ResponseCallback#onResponse` we write a separate document each time we write which results in a non-valid JSON document. We can either write a large JSON array or we could write to several different files.

**Comment by brodin** [comment]
@luuse dose this work ok now?

**Comment by luuse** [comment]
As of 271cad05c4c8853f96b0013dd56ed95f46cc42b3 it works.
