### ISSUE TITLE
Remove the infobox trait

### ISSUE THREAD

**Issue by luuse** [luuse/spock#21]
We want to bring meaning to the information we find and the InfoBoxTrait currently only parses key values and makes it hard to utilize the tree structure to gradually look for more and more specific information. We should just remove this trait and/or split it up into smaller traits that look for categorized information.

**Comment by brodin** [comment]
https://github.com/luuse/spock/commit/db532d1691a8a0a6b5eed1bf6ebbd7a501e70c6d
